name: attendance_app
description: A professional offline Attendance Management App using Clean Architecture.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Local Persistence
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Dependency Injection
  get_it: ^7.6.0
  
  # Functional Programming (for Either)
  fpdart: ^1.1.0
  
  # UI & Utilities
  google_fonts: ^6.1.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
